<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ApplicantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('applicanttbl')->insert([
        	'accountid' => 3,
        	'lastname' => 'Gallardo',
            'firstname' => 'Christian',
            'middlename' => 'Ansing',
            'suffix' => null,
            'cityaddress' => 'Dalanghita St.',
            'cityaddresscity' => 'Antipolo City',
            'cityaddressprovince' => 'Rizal',
            'provincialaddress' => null,
            'provincialaddresscity' => null,
            'provincialaddressprovince' => null,
            'latitude' => 14.5979692,
            'longitude' => 121.1351785,
            'gender' => 'Male',
            'picture' => 'default.png',
            'dateofbirth' => '1998-01-23',
            'placeofbirth' => 'Quezon City',
            'age' => 19,
            'civilstatus' => 'Single',
            'religion' => 'Born-Again Christian',
            'bloodtype' => 'A',
            'appcontactno' => '09751439665',
            'workexp' => 0,
            'height' => 172,
            'weight' => 68,
            'license' => 'aaa11111111111',
            'licenseexpiration' => '2020-10-10',
            'sss' => '11-1111111-1',
            'philhealth' => '11-111111111-1',
            'pagibig' => '1111-1111-1111',
            'tin' => '111-111-111-111',
            'hobby' => null,
            'skill' => null,
            'spousename' => null,
            'spousedateofbirth' => null,
            'spouseoccupation' => null,
            'contactperson' => 'Honorato A. Gallardo Jr.',
            'contactno' => '09352752342',
        	'status' => 0,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        DB::table('applicanttbl')->insert([
            'accountid' => 4,
            'lastname' => 'Egos',
            'firstname' => 'John Christopher',
            'middlename' => 'Gregorio',
            'suffix' => null,
            'cityaddress' => '116 Bagong Kalsada St.',
            'cityaddresscity' => 'Navotas',
            'cityaddressprovince' => 'Metro Manila',
            'provincialaddress' => null,
            'provincialaddresscity' => null,
            'provincialaddressprovince' => null,
            'latitude' => 14.6714345,
            'longitude' => 120.9334183,
            'gender' => 'Male',
            'picture' => 'default.png',
            'dateofbirth' => '1999-07-16',
            'placeofbirth' => 'Manila',
            'age' => 18,
            'civilstatus' => 'Single',
            'religion' => 'Catholic',
            'bloodtype' => 'A',
            'appcontactno' => '09192133161',
            'workexp' => 0,
            'height' => 167,
            'weight' => 128,
            'license' => 'bbb22222222222',
            'licenseexpiration' => '2020-10-10',
            'sss' => '22-2222222-2',
            'philhealth' => '22-222222222-2',
            'pagibig' => '2222-2222-2222',
            'tin' => '222-222-222-222',
            'hobby' => null,
            'skill' => null,
            'spousename' => null,
            'spousedateofbirth' => null,
            'spouseoccupation' => null,
            'contactperson' => 'Teodulo Egos',
            'contactno' => '09294001021',
            'status' => 0,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()->addDays(-13),
        ]);

        DB::table('applicanttbl')->insert([
            'accountid' => 5,
            'lastname' => 'Tolentino',
            'firstname' => 'Roy Emmanuel',
            'middlename' => 'Tena',
            'suffix' => null,
            'cityaddress' => '13D Sta. Catalina St.',
            'cityaddresscity' => 'Quezon City',
            'cityaddressprovince' => 'Metro Manila',
            'provincialaddress' => null,
            'provincialaddresscity' => null,
            'provincialaddressprovince' => null,
            'latitude' => 14.6864228,
            'longitude' => 121.0840108,
            'gender' => 'Male',
            'picture' => 'default.png',
            'dateofbirth' => '1999-12-31',
            'placeofbirth' => 'Quezon City',
            'age' => 19,
            'civilstatus' => 'Single',
            'religion' => 'Born-Again Christian',
            'bloodtype' => 'O',
            'appcontactno' => '09269315798',
            'workexp' => 0,
            'height' => 160,
            'weight' => 48,
            'license' => 'ccc33333333333',
            'licenseexpiration' => '2020-10-10',
            'sss' => '33-1111111-3',
            'philhealth' => '33-333333333-3',
            'pagibig' => '3333-3333-3333',
            'tin' => '333-333-333-333',
            'hobby' => null,
            'skill' => null,
            'spousename' => null,
            'spousedateofbirth' => null,
            'spouseoccupation' => null,
            'contactperson' => 'Marietta Tolentino',
            'contactno' => '09464774597',
            'status' => 0,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()->addDays(-23),
        ]);

        DB::table('applicanttbl')->insert([
            'accountid' => 6,
            'lastname' => 'Astudillo',
            'firstname' => 'Jamee Camille',
            'middlename' => 'Hetigan',
            'suffix' => null,
            'cityaddress' => '3 Sto. Rosario St.',
            'cityaddresscity' => 'Mandaluyong City',
            'cityaddressprovince' => 'Metro Manila',
            'provincialaddress' => null,
            'provincialaddresscity' => null,
            'provincialaddressprovince' => null,
            'latitude' => 14.5764227,
            'longitude' => 121.0333276,
            'gender' => 'Female',
            'picture' => 'default.png',
            'dateofbirth' => '1997-07-05',
            'placeofbirth' => 'Manila',
            'age' => 20,
            'civilstatus' => 'Single',
            'religion' => 'Catholic',
            'bloodtype' => 'A',
            'appcontactno' => '09366975144',
            'workexp' => 0,
            'height' => 152,
            'weight' => 49,
            'license' => 'ddd44444444444',
            'licenseexpiration' => '2020-10-10',
            'sss' => '44-4444444-4',
            'philhealth' => '44-444444444-4',
            'pagibig' => '4444-4444-4444',
            'tin' => '444-444-444-444',
            'hobby' => null,
            'skill' => null,
            'spousename' => null,
            'spousedateofbirth' => null,
            'spouseoccupation' => null,
            'contactperson' => 'Christa Janella Astudillo',
            'contactno' => '09263709030',
            'status' => 0,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()->addDays(-48),
        ]);
    }
}
